name: Build Documentation
on:
  push:
    paths:
      - 'Documentation/**.tex'
      - '.github/workflows/docs.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Documentation directory if it doesn't exist
        run: mkdir -p Documentation
        
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Documentation/ImagoCrafter.tex
          working_directory: .
          
      - name: List files (debug)
        run: |
          ls -la
          ls -la Documentation || echo "Documentation directory not found"
          
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Documentation-PDF
          path: Documentation/ImagoCrafter.pdf
          if-no-files-found: error